version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: niloxx/davil:0.1
    environment:
      - DOCKER_IP
    deploy:
      replicas: 2
      resources:
        limits:
          cpus: "0.4"
          memory: 500M
      restart_policy:
        condition: on-failure
    ports:
      - "5000:5000"
      - "5006:5006"
    networks:
      - webnet
networks:
  webnet:
